export const CREATE_TODO = 'TODO/CREATE_TODO'
export const EDIT_TODO = 'TODO/EDIT_TODO'
export const TOGGLE_TODO = 'TODO/TOGGLE_TODO'
export const DELETE_TODO = 'TODO/DELETE_TODO'
export const CREATE_BUCKET = 'BUCKET/CREATE_BUCKET'
export const DELETE_BUCKET = 'BUCKET/DELETE_BUCKET'
export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE'
}